# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff0750df15c9ec125ffd771c63a8c35644469adcdfd7bf492931292ea30151107356a4fcfe6912e605afb9a2c7428e92b671498c2c29cbee707d7cb22b7826cc

test:
  secret_key_base: a08989dc19c6b3bda81124f9ec10133f766e2e778af0ab02f031eda8e0a453a979f58e46c9d2f062488bb60cbfd5c60db685525a9b26821d80a2c879716476e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
